### ISSUE TITLE
节点label为字符串时，能否增加样式的扩展

### ISSUE THREAD

**Issue by jiang385** [AdamRobertHall/react-native-tree#2]
let textNode;
        if (typeof label === 'string') {
            textNode = <Text style={textStyle}>{label} </Text>
        } else {
            textNode = <View>{label}</View>
        }

虽然label非字符串类型时的确能自定义节点展示的样式，但是要遍历数据修改，有点麻烦。

**Comment by AdamRobertHall** [comment]
可以按你的想法改，改好后提交合并请求
